version: '3.9'

services:
  xls:
    build: .
    container_name: xls
    restart: always
    ports:
      - "8080:8080"
    networks:
      - test-mission_default

  certbot2:
    image: certbot/certbot
    container_name: certbot2
    volumes:
      - test-mission_etc-letsencrypt:/etc/letsencrypt
      - test-mission_www-html:/var/www/html
    command: certonly --webroot -w /var/www/html --email anakinnikitaa@gmail.com -d denis.anakinnikita.ru --cert-name=denis --key-type rsa --agree-tos
    ports:
      - "6080:80"
    networks:
      - test-mission_default

volumes:
  test-mission_www-html:
    external: true
  test-mission_etc-letsencrypt:
    external: true

networks:
  test-mission_default:
    external: true